# Generated by Django 3.2 on 2021-08-06 14:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vehicle', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('contact_numbers', django.contrib.postgres.fields.ArrayField(base_field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None), size=None)),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), size=None)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('registration_type', models.CharField(max_length=30)),
                ('registration_number', models.CharField(max_length=20)),
                ('contact_person_name', models.CharField(max_length=30)),
                ('contact_person_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('contact_person_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('slot_length', models.PositiveIntegerField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='common.city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.partner')),
                ('supported_vehicle_types', models.ManyToManyField(blank=True, related_name='stores', to='vehicle.VehicleType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_blocking', models.BooleanField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='store.bay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bay',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bays', to='store.store'),
        ),
        migrations.AddField(
            model_name='bay',
            name='supported_vehicle_types',
            field=models.ManyToManyField(blank=True, to='vehicle.VehicleType'),
        ),
        migrations.CreateModel(
            name='PriceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveIntegerField()),
                ('time_interval', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('bays', models.ManyToManyField(help_text='BUG: Do no edit this field, if you want to change bays delete this instance and create another one', to='store.Bay')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricetimes', to='common.service')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricetimes', to='store.store')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricetimes', to='vehicle.vehicletype')),
            ],
            options={
                'unique_together': {('vehicle_type', 'service')},
            },
        ),
    ]
