# Generated by Django 3.2 on 2021-05-11 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='vehicles_allowed',
        ),
        migrations.AddField(
            model_name='store',
            name='supported_vehicle_types',
            field=models.ManyToManyField(blank=True, related_name='stores', to='store.VehicleType'),
        ),
        migrations.AlterField(
            model_name='pricetime',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='store.vehicletype'),
        ),
        migrations.AlterField(
            model_name='service',
            name='supported_vehicle_types',
            field=models.ManyToManyField(blank=True, related_name='services', to='store.VehicleType'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicle_model',
            field=models.CharField(choices=[('1_two', 'Standard'), ('2_two', 'Bullet'), ('3_two', 'Sports Bike'), ('4_two', 'Premium Bike'), ('1_four', 'Sedan'), ('2_four', 'H-Back'), ('3_four', 'SUV'), ('4_four', 'Luxury')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicle_type',
            field=models.CharField(choices=[('two', 'Two Wheeler'), ('four', 'Four Wheeler')], max_length=50),
        ),
    ]
