# Generated by Django 3.2 on 2021-04-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicle_model',
            field=models.CharField(choices=[('1_two', 'Standard'), ('2_two', 'Bullet'), ('3_two', 'Sports Bike'), ('4_two', 'Premium Bike'), ('1_four', 'Sedan'), ('2_four', 'H-Back'), ('3_four', 'SUV'), ('4_four', 'Luxury')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicle_type',
            field=models.CharField(choices=[(2, 'Two Wheeler'), (4, 'Four Wheeler')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='pricetime',
            unique_together={('vehicle_type', 'service')},
        ),
        migrations.RemoveField(
            model_name='pricetime',
            name='bays',
        ),
    ]
