# Generated by Django 3.2 on 2021-04-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bay',
            old_name='vehicle_type',
            new_name='supported_vehicle_types',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='vehicles_allowed',
            new_name='supported_vehicle_types',
        ),
    ]
