# Generated by Django 3.2 on 2021-08-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20210820_2316'),
        ('vehicle', '0002_vehicletype_description'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='stores', to='common.Service'),
        ),
        migrations.AlterUniqueTogether(
            name='pricetime',
            unique_together={('vehicle_type', 'service', 'store')},
        ),
    ]
