# Generated by Django 3.2 on 2021-08-14 01:21

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetime',
            name='images',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
    ]
