# Generated by Django 3.2 on 2021-06-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210511_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
