# Generated by Django 3.2 on 2021-08-07 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210807_0544'),
        ('store', '0002_auto_20210807_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.partner'),
        ),
    ]
