# Generated by Django 3.2 on 2021-04-29 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210430_0107'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricetime',
            unique_together={('vehicle_type', 'service')},
        ),
    ]
