# Generated by Django 3.2 on 2021-08-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_pricetime_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetime',
            name='bays',
            field=models.ManyToManyField(blank=True, help_text='BUG: Do no edit this field, if you want to change bays delete this instance and create another one', to='store.Bay'),
        ),
    ]
