# Generated by Django 3.2 on 2021-08-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210820_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='slot_length',
        ),
    ]
