# Generated by Django 3.2 on 2021-08-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_pricetime_bays'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_locked_for_salesman',
            field=models.BooleanField(default=False),
        ),
    ]
