# Generated by Django 3.2 on 2021-08-29 01:32

from django.db import migrations, models
import custom_admin_arrayfield.models.fields
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_store_slot_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_times',
            field=custom_admin_arrayfield.models.fields.ArrayField(base_field=models.JSONField(), help_text='{"closing_time": "18:00:00", "opening_time": "09:00:00"}', size=None, validators=[store.validators.JSONSchemaValidator(limit_value={'properties': {'items': {'type': 'object'}, 'maxItems': 7, 'minItems': 7}, 'required': ['my_key'], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'array'})]),
        ),
    ]
