# Generated by Django 3.2 on 2021-04-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_pricetime_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bay',
            name='supported_vehicle_types',
            field=models.ManyToManyField(blank=True, to='store.VehicleType'),
        ),
        migrations.AlterField(
            model_name='service',
            name='supported_vehicle_types',
            field=models.ManyToManyField(blank=True, to='store.VehicleType'),
        ),
    ]
