# Generated by Django 3.2 on 2021-08-07 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210807_0544'),
        ('store', '0004_auto_20210807_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.partner'),
        ),
    ]
