# Generated by Django 3.2 on 2021-06-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210624_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicletype',
            old_name='vehicle_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='vehicletype',
            old_name='vehicle_type',
            new_name='wheel',
        ),
    ]
