# Generated by Django 3.2 on 2021-08-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_is_locked_for_salesman'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_verified_by_admin',
            field=models.BooleanField(default=False, verbose_name='Verified by admin'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_locked_for_salesman',
            field=models.BooleanField(default=False, verbose_name='Locked for salesmanm if True salesman cannot edit this'),
        ),
    ]
