# Generated by Django 3.2 on 2021-09-17 20:52

from django.db import migrations, models
import custom_admin_arrayfield.models.fields
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_store_store_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_times',
            field=custom_admin_arrayfield.models.fields.ArrayField(base_field=models.JSONField(), help_text='{"closing_time": "18:00", "opening_time": "09:00"}', size=None, validators=[store.validators.JSONSchemaValidator(limit_value={'items': {'additionalProperties': False, 'properties': {'closing_time': {'pattern': '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$', 'type': 'string'}, 'opening_time': {'pattern': '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$', 'type': 'string'}}, 'type': 'object'}, 'maxItems': 7, 'minItems': 7, 'required': ['my_key'], 'type': 'array'})]),
        ),
    ]
