# Generated by Django 3.2 on 2021-09-17 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_store_store_times'),
        ('store', '0004_auto_20210917_0127'),
    ]

    operations = [
    ]
