# Generated by Django 3.2 on 2021-08-07 15:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_store_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='store',
            name='thumbnail',
            field=models.URLField(),
        ),
    ]
