# Generated by Django 3.2 on 2021-09-17 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_store_store_times'),
        ('store', '0005_merge_20210917_0209'),
    ]

    operations = [
    ]
