# Generated by Django 3.2 on 2021-07-08 15:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210624_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('imagess', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to=''), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='store',
        ),
        migrations.RemoveField(
            model_name='service',
            name='supported_vehicle_types',
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
