# Generated by Django 3.2 on 2021-09-29 21:23

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_merge_20210917_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_times',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.JSONField(), help_text='{"closing_time": "18:00", "opening_time": "09:00"}', size=None, validators=[store.validators.JSONSchemaValidator(limit_value={'items': {'additionalProperties': False, 'properties': {'closing_time': {'pattern': '^([01]?[0-9]|2[0-3]):[0-5][0-9]$', 'type': 'string'}, 'opening_time': {'pattern': '^([01]?[0-9]|2[0-3]):[0-5][0-9]$', 'type': 'string'}}, 'type': 'object'}, 'maxItems': 7, 'minItems': 7, 'required': ['my_key'], 'type': 'array'})]),
        ),
    ]
