# Generated by Django 3.2 on 2021-08-07 15:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210807_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='store',
            name='opening_time',
        ),
        migrations.AddField(
            model_name='store',
            name='store_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
