# Generated by Django 3.2 on 2021-07-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('store', '0007_auto_20210708_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.RemoveField(
            model_name='storeimage',
            name='store',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(default='TEST', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='common.city'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='StoreImage',
        ),
    ]
