# Generated by Django 3.2 on 2021-08-10 11:10

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210807_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='contact_numbers',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None), size=None),
        ),
        migrations.AlterField(
            model_name='store',
            name='emails',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.EmailField(max_length=254), size=None),
        ),
        migrations.AlterField(
            model_name='store',
            name='images',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_times',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.JSONField(), size=None),
        ),
    ]
