# Generated by Django 3.2 on 2021-10-26 20:08

import custom_admin_arrayfield.models.fields
from django.db import migrations, models
import phonenumber_field.modelfields
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_store_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetime',
            name='images',
            field=custom_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='store',
            name='contact_numbers',
            field=custom_admin_arrayfield.models.fields.ArrayField(base_field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None), size=None),
        ),
        migrations.AlterField(
            model_name='store',
            name='images',
            field=custom_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_times',
            field=custom_admin_arrayfield.models.fields.ArrayField(base_field=models.JSONField(), help_text='{"closing_time": "18:00", "opening_time": "09:00"}', size=None, validators=[store.validators.JSONSchemaValidator(limit_value={'items': {'additionalProperties': False, 'properties': {'closing_time': {'pattern': '^([01]?[0-9]|2[0-3]):[0-5][0-9]$', 'type': 'string'}, 'opening_time': {'pattern': '^([01]?[0-9]|2[0-3]):[0-5][0-9]$', 'type': 'string'}}, 'type': 'object'}, 'maxItems': 7, 'minItems': 7, 'required': ['my_key'], 'type': 'array'})]),
        ),
    ]
