# Generated by Django 3.2 on 2021-08-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210810_1640'),
        ('store', '0008_store_pincode'),
    ]

    operations = [
    ]
