# Generated by Django 3.2 on 2022-01-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211026_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='display_days_open',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='display_opening_closing_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
