# Generated by Django 3.2 on 2021-08-13 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210807_0544'),
        ('store', '0009_merge_0008_auto_20210810_1640_0008_store_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='accounts.salesman'),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.storeowner'),
        ),
        migrations.AlterField(
            model_name='store',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='accounts.partner'),
        ),
    ]
