# Generated by Django 3.2 on 2022-01-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20220113_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='intra_day_time',
            field=models.SmallIntegerField(default=360),
        ),
    ]
