# Generated by Django 3.2 on 2021-08-13 05:03

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210813_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_times',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.JSONField(), help_text='{"closing_time": "18:00:00", "opening_time": "09:00:00"}', size=None),
        ),
    ]
