# Generated by Django 3.2 on 2022-01-25 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_store_intra_day_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetime',
            name='bays',
        ),
    ]
