# Generated by Django 3.2 on 2022-01-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_pricetime_bays'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['reputation']},
        ),
        migrations.AddField(
            model_name='store',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
