# Generated by Django 3.2 on 2022-01-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20220128_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-reputation']},
        ),
        migrations.AlterField(
            model_name='store',
            name='reputation',
            field=models.IntegerField(default=0, help_text='Used to order stores, higher reputation means higher priority'),
        ),
    ]
