# Generated by Django 3.2 on 2021-07-20 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0004_alter_serviceimage_service'),
        ('common', '0003_service'),
        ('store', '0013_auto_20210709_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetime',
            name='bays',
            field=models.ManyToManyField(help_text='BUG: Do no edit this field, if you want to change bays delete this instance and create another one', to='store.Bay'),
        ),
        migrations.AlterField(
            model_name='pricetime',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.service'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
