# Generated by Django 3.2 on 2022-02-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20220128_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetime',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricetime',
            name='mrp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
