# Generated by Django 3.2 on 2021-07-20 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_service'),
        ('vehicle', '0001_initial'),
        ('store', '0014_auto_20210720_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetime',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pricetimes', to='store.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricetime',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricetimes', to='common.service'),
        ),
        migrations.AlterField(
            model_name='pricetime',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricetimes', to='vehicle.vehicletype'),
        ),
    ]
