# Generated by Django 3.2 on 2022-02-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20220209_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetime',
            name='mrp',
            field=models.PositiveIntegerField(default=0, help_text='Display field only, if there is some mrp show striked value'),
        ),
    ]
