# Generated by Django 3.2 on 2021-07-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_store_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricetime',
            old_name='amount',
            new_name='price',
        ),
    ]
