# Generated by Django 3.2 on 2021-07-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rename_amount_pricetime_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slot_interval',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
