# Generated by Django 3.2 on 2021-08-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rename_amount_pricetime_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetime',
            name='description',
            field=models.TextField(default='helo nicensldfj ls kld klfsd fljdkl fjldk fjlksd fklsdkl fsdjklj sdkl fkldkl f'),
            preserve_default=False,
        ),
    ]
