# Generated by Django 3.2 on 2021-07-24 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_bay_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='store.bay'),
        ),
    ]
