# Generated by Django 3.2 on 2022-05-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20220227_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetime',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR'), ('EUR', 'EUR')], default='INR', max_length=3),
        ),
    ]
