# Generated by Django 3.2 on 2022-06-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_pricetime_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_hamper_offer',
            field=models.BooleanField(default=False),
        ),
    ]
