# Generated by Django 3.2 on 2021-08-01 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_pricetime_description'),
        ('store', '0022_alter_event_bay'),
    ]

    operations = [
    ]
