# Generated by Django 3.2 on 2021-08-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210815_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='code',
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
