# Generated by Django 3.2 on 2021-08-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20210820_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
