# Generated by Django 3.2 on 2021-12-19 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_city_upcoming'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
