# Generated by Django 3.2 on 2022-01-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_servicetag_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetag',
            name='thumbnail',
            field=models.ImageField(default='/service_tags/default.png', upload_to='service_tags'),
        ),
    ]
