# Generated by Django 3.2 on 2022-01-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_servicetag_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicetag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
