# Generated by Django 3.2 on 2022-01-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_service_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-reputation']},
        ),
        migrations.AlterModelOptions(
            name='servicetag',
            options={'ordering': ['-reputation']},
        ),
        migrations.AddField(
            model_name='service',
            name='reputation',
            field=models.IntegerField(default=0, help_text='Used to order services, higher reputation means higher priority'),
        ),
        migrations.AddField(
            model_name='servicetag',
            name='reputation',
            field=models.IntegerField(default=0, help_text='Used to order tags, higher reputation means higher priority'),
        ),
    ]
