# Generated by Django 3.2 on 2022-02-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20220128_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetag',
            name='banner',
            field=models.ImageField(default='/service_tags/banner.png', upload_to='service_tags'),
        ),
    ]
