# Generated by Django 3.2 on 2022-02-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_servicetag_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetag',
            name='banner',
            field=models.ImageField(upload_to='service_tags'),
        ),
        migrations.AlterField(
            model_name='servicetag',
            name='thumbnail',
            field=models.ImageField(upload_to='service_tags'),
        ),
    ]
