# Generated by Django 3.2 on 2022-05-26 18:06

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20220225_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
