# Generated by Django 3.2 on 2021-08-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210807_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_salesman',
        ),
    ]
