# Generated by Django 3.2 on 2021-09-17 20:52

from django.db import migrations, models
import custom_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_tokens',
            field=custom_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=230, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='registered_topics',
            field=custom_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), default=list, size=None),
        ),
    ]
