# Generated by Django 3.2 on 2021-09-17 21:25

from django.db import migrations, models
import custom_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_registered_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fcm_tokens',
            field=custom_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=230, null=True), default=list, size=None),
        ),
    ]
