# Generated by Django 3.2 on 2021-08-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wheel', models.CharField(choices=[('two', 'Two Wheeler'), ('four', 'Four Wheeler')], max_length=50)),
                ('model', models.CharField(choices=[('standard', 'Standard'), ('cruisers', 'Cruisers'), ('sports_bike', 'Sports Bike'), ('premium_bike', 'Premium Bike'), ('sedan', 'Sedan'), ('h_back', 'H-Back'), ('suv', 'SUV'), ('luxury', 'Luxury')], max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
