# Generated by Django 3.2 on 2021-08-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wheel', models.CharField(choices=[('two', 'Two Wheeler'), ('four', 'Four Wheeler'), ('commercial', 'Commercial')], max_length=50)),
                ('model', models.CharField(choices=[('standard', 'Standard'), ('cruisers', 'Cruisers'), ('sports_bike', 'Sports Bike'), ('premium_bike', 'Premium Bike'), ('sedan', 'Sedan'), ('h_back', 'H-Back'), ('suv', 'SUV'), ('luxury', 'Luxury'), ('limo', 'Limo'), ('truck', 'trudk'), ('bada_truck', 'bada trick')], max_length=50, primary_key=True, serialize=False)),
                ('image', models.URLField(default='https://d3to388m2zu1ph.cloudfront.net/media/questions/g916_1_1.png')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
