# Generated by Django 3.2 on 2021-08-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
