# Generated by Django 3.2 on 2021-08-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicletype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='model',
            field=models.CharField(help_text='Bike, Scooty, Sedan, Hachback, SUV, Truck, Bada Wala Truck', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='wheel',
            field=models.CharField(help_text='Two Wheeler, Three Wheeler, Four Wheeler, Commercial', max_length=50),
        ),
    ]
