# Generated by Django 3.2 on 2021-08-25 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20210825_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='wheel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_types', to='vehicle.wheel'),
        ),
    ]
