# Generated by Django 3.2 on 2021-09-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_vehiclebrand_vehiclemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='image',
            field=models.URLField(default='https://d3to388m2zu1ph.cloudfront.net/media/questions/g916_1_1.png'),
        ),
    ]
