# Generated by Django 3.2 on 2021-10-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_wheel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
