# Generated by Django 3.2 on 2022-05-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_auto_20220303_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRegistrationData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reg_num', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('data', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
