# Generated by Django 3.2 on 2022-06-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_vehicleregistrationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclebrand',
            name='image',
            field=models.URLField(default='https://cdn.autoave.in/population_data/85e5eb14-606a-4deb-8761-f548bf84dbe6.jpg'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='image',
            field=models.URLField(default='https://cdn.autoave.in/population_data/85e5eb14-606a-4deb-8761-f548bf84dbe6.jpg'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='image',
            field=models.URLField(default='https://cdn.autoave.in/population_data/85e5eb14-606a-4deb-8761-f548bf84dbe6.jpg'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='image',
            field=models.URLField(default='https://cdn.autoave.in/population_data/85e5eb14-606a-4deb-8761-f548bf84dbe6.jpg'),
        ),
    ]
