# Generated by Django 3.2 on 2021-08-15 18:43

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0001_initial'),
        ('vehicle', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Not Paid'), (1, 'Payment Done'), (2, 'Not Attended'), (3, 'Service Started'), (4, 'Service Completed')])),
                ('status_changed_time', models.DateTimeField(default=datetime.datetime.now)),
                ('otp', models.CharField(max_length=4)),
                ('is_refunded', models.BooleanField(default=False)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.consumer')),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.event')),
                ('price_times', models.ManyToManyField(related_name='bookings', to='store.PriceTime')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='store.store')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='vehicle.vehicletype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_only_rating', models.BooleanField(default=True)),
                ('review_description', models.CharField(blank=True, max_length=250, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=''), blank=True, null=True, size=None)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='booking.booking')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.consumer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refund_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Paid'), (2, 'Cancelled')])),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='booking.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_status', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=10)),
                ('mode_of_payment', models.CharField(max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='booking.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
