# Generated by Django 3.2 on 2021-04-29 11:56

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_id', models.CharField(max_length=8)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Started'), (1, 'Done'), (2, 'Error')])),
                ('status_changed_time', models.DateTimeField(default=datetime.datetime.now)),
                ('otp', models.CharField(max_length=4)),
                ('is_refunded', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_status', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=10)),
                ('mode_of_payment', models.CharField(max_length=20)),
                ('amount', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refund_status', models.IntegerField(choices=[(0, 'Started'), (1, 'COMPLETED'), (2, 'Error')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_only_rating', models.BooleanField(default=True)),
                ('review_description', models.CharField(blank=True, max_length=250, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=''), blank=True, null=True, size=None)),
                ('rating', models.FloatField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='booking.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
