# Generated by Django 3.2 on 2021-08-07 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_store_partner'),
        ('accounts', '0002_auto_20210807_0544'),
        ('vehicle', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.consumer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store.event'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='otp',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_times',
            field=models.ManyToManyField(related_name='bookings', to='store.PriceTime'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='store.store'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='vehicle.vehicletype'),
        ),
    ]
