# Generated by Django 3.2 on 2021-04-29 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('accounts', '0002_auto_20210425_1623'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.consumer'),
        ),
        migrations.AddField(
            model_name='refund',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='booking.booking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='booking.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.consumer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.event'),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.pricetime'),
        ),
        migrations.AddField(
            model_name='booking',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.store'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.vehicletype'),
        ),
    ]
