# Generated by Django 3.2 on 2021-04-30 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210430_1459'),
        ('booking', '0003_rename_user_review_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store.event'),
        ),
    ]
