# Generated by Django 3.2 on 2021-08-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210820_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
