# Generated by Django 3.2 on 2021-08-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20210821_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Not Paid'), (10, 'Payment Done'), (20, 'Payment Failed'), (30, 'Not Attended'), (40, 'Service Started'), (50, 'Service Completed')]),
        ),
    ]
