# Generated by Django 3.2 on 2021-09-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210826_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'NOT_PAID'), (10, 'PAYMENT_DONE'), (20, 'PAYMENT_FAILED'), (30, 'NOT_ATTENDED'), (40, 'SERVICE_STARTED'), (50, 'SERVICE_COMPLETED')]),
        ),
    ]
