# Generated by Django 3.2 on 2021-09-29 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_wheel_image'),
        ('booking', '0008_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='vehicle.vehiclemodel'),
        ),
    ]
