# Generated by Django 3.2 on 2021-12-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20211217_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationrequest',
            name='status',
            field=models.TextField(blank=True, help_text='To be filled by an Admin', null=True),
        ),
    ]
