# Generated by Django 3.2 on 2021-12-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20211217_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='status_changed_time',
            new_name='booking_status_changed_time',
        ),
    ]
