# Generated by Django 3.2 on 2021-12-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20211221_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_refunded',
        ),
    ]
