# Generated by Django 3.2 on 2022-01-03 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_email'),
        ('store', '0009_auto_20211026_2008'),
        ('booking', '0019_remove_booking_is_refunded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('discount_percentage', models.IntegerField(default=10)),
                ('max_discount', models.IntegerField(default=0)),
                ('max_redeem_count', models.IntegerField(default=10, help_text='Maximum number of times a offer can be used in total, 0 for unlimited')),
                ('max_redeem_count_per_cosumer', models.IntegerField(default=2, help_text='Maximum number of times a offer can be used by one user, 0 for unlimited')),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('linked_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferRedeem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeems', to='accounts.consumer')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeems', to='booking.offer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='couponredeem',
            name='consumer',
        ),
        migrations.RemoveField(
            model_name='couponredeem',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='CouponRedeem',
        ),
    ]
