# Generated by Django 3.2 on 2022-01-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20220103_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='offer_banners'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_promotional',
            field=models.BooleanField(default=False),
        ),
    ]
