# Generated by Django 3.2 on 2022-01-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_auto_20220103_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='is_promotional',
            new_name='is_promo',
        ),
    ]
