# Generated by Django 3.2 on 2022-01-19 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_rename_is_promotional_offer_is_promo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
