# Generated by Django 3.2 on 2022-01-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_delete_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_multi_day',
            field=models.BooleanField(default=False),
        ),
    ]
