# Generated by Django 3.2 on 2022-01-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_booking_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rp_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
