# Generated by Django 3.2 on 2022-01-29 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_payment_rp_signature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
    ]
