# Generated by Django 3.2 on 2022-02-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20220128_0051'),
        ('booking', '0028_auto_20220205_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='applicable_services',
            field=models.ManyToManyField(blank=True, related_name='applicable_on_offers', to='common.Service'),
        ),
        migrations.AddField(
            model_name='offer',
            name='services_to_add',
            field=models.ManyToManyField(blank=True, related_name='will_be_added_on_offers', to='common.Service'),
        ),
    ]
