# Generated by Django 3.2 on 2022-03-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_auto_20220217_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_by_webhook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['razorpay_order_id'], name='booking_boo_razorpa_4eb8b3_idx'),
        ),
    ]
