# Generated by Django 3.2 on 2022-01-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlogging',
            name='content',
        ),
        migrations.RemoveField(
            model_name='errorlogging',
            name='location',
        ),
        migrations.AddField(
            model_name='errorlogging',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlogging',
            name='exception',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlogging',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
