# Generated by Django 3.2 on 2022-06-05 20:50

import custom_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0005_auto_20220122_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendGridEmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('smtpId', models.CharField(max_length=300)),
                ('event', models.CharField(max_length=200)),
                ('category', custom_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('sgEventId', models.CharField(max_length=200)),
                ('sgMessageId', models.CharField(max_length=300)),
                ('response', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('useragent', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
