# Generated by Django 3.2 on 2022-06-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0007_auto_20220605_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_city', models.CharField(blank=True, max_length=100, null=True)),
                ('to_city', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
