# Generated by Django 3.2 on 2022-06-10 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0008_transportenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportenquiry',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transportenquiry',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
