# Generated by Django 3.2 on 2022-06-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0009_auto_20220610_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportenquiry',
            name='whatsapp_group_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transportenquiry',
            name='status',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
