# Generated by Django 3.2 on 2021-08-06 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('completed', models.BooleanField(default=False)),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='accounts.consumer')),
                ('items', models.ManyToManyField(related_name='carts', to='store.PriceTime')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
