# Generated by Django 3.2 on 2022-01-06 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_rename_is_promotional_offer_is_promo'),
        ('cart', '0002_cart_vehicle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='booking.offer'),
        ),
    ]
