# Generated by Django 3.2 on 2022-01-13 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_rename_is_promotional_offer_is_promo'),
        ('cart', '0003_cart_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='booking.offer'),
        ),
    ]
