# Generated by Django 3.2 on 2021-07-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rename_amount_pricetime_price'),
        ('cart', '0004_rename_user_cart_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='store.store'),
        ),
    ]
